parameters:
- name: dockerImage
  type: string
- name: dockerImageTag
  type: string
- name: azureSubscription
  type: string
- name: resourceGroup
  type: string
- name: containerAppName
  type: string

steps:
  - task: AzureContainerApps@1
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      containerAppName: ${{ parameters.containerAppName }}
      resourceGroup: ${{ parameters.resourceGroup }}
      imageToDeploy: ${{ parameters.dockerImage }}:${{ parameters.dockerImageTag }}
